-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH,'yyyy-mm-dd')
FROM MEMBER_PROFILE
WHERE TLNO != 'NULL' AND GENDER ='W' AND
    TO_CHAR(DATE_OF_BIRTH,'mm')='03'
ORDER BY MEMBER_ID ASC;