-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_FORMAT
FROM MEMBER_PROFILE
WHERE NOT TLNO IS NULL AND GENDER ='W' AND
    DATE_FORMAT(DATE_OF_BIRTH,'%m')='03'
ORDER BY MEMBER_ID ASC;